---
- name: Populate service facts
  ansible.builtin.service_facts:

- name: Stop Sonarr
  ansible.builtin.service:
    name: sonarr
    state: stopped
  notify:
    - Start Sonarr
  when: '"sonarr.service" in services'
  tags:
    # this will always stop/start radarr, because we don't want to potentially
    # install a new version or update the config file below while it's running.
    - molecule-idempotence-notest

- name: Install gpg
  ansible.builtin.package:
    name: gpg
    state: present

- name: Add Mono repository apt key
  ansible.builtin.apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF

- name: Add Mono repository
  ansible.builtin.apt_repository:
    repo: "deb https://download.mono-project.com/repo/debian stable-buster main"
    state: present
    filename: mono-official-stable.list

- name: Add MediaArea repository apt key
  ansible.builtin.apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: C5CDF62C7AE05CC847657390C10E11090EC0E438

- name: Add MediaArea repository
  ansible.builtin.apt_repository:
    repo: "deb https://mediaarea.net/repo/deb/debian buster main"
    state: present
    filename: mediaarea.list

- name: Add Sonarr repository apt key
  ansible.builtin.apt_key:
    keyserver: hkp://keyserver.ubuntu.com:80
    id: 2009837CBFFD68F45BC180471F4F90DE2A9B4BF8

- name: Add Sonarr repository
  ansible.builtin.apt_repository:
    repo: "deb https://apt.sonarr.tv/debian buster main"
    state: present
    filename: sonarr.list

- name: Install Sonarr
  ansible.builtin.package:
    name: sonarr
    state: present
  notify:
    - Start Sonarr

- name: Create media group
  ansible.builtin.group:
    name: media
    state: present
    gid: "{{ sonarr__media_group_id }}"

- name: Add sonarr user to group media
  ansible.builtin.user:
    name: sonarr
    groups: media
    state: present

- name: Stop Sonarr before touching config file
  ansible.builtin.service:
    name: sonarr
    state: stopped
  notify:
    - Start Sonarr
  tags:
    # this will always stop/start radarr, because we don't want to potentially
    # install a new version or update the config file below while it's running.
    - molecule-idempotence-notest

- name: Check if Sonarr config file exists
  ansible.builtin.stat:
    path: /var/lib/sonarr/config.xml
  register: soco

- name: Configure UrlBase in Sonarr (existing config)
  ansible.builtin.lineinfile:
    path: "/var/lib/sonarr/config.xml"
    regexp: "^  <UrlBase>.*</UrlBase>"
    line: "  <UrlBase>/sonarr</UrlBase>"
    insertbefore: "</Config>"
  when: soco.stat.exists

- name: Create Sonarr datadir
  ansible.builtin.file:
    path: /var/lib/sonarr
    state: directory
    mode: "0755"
    owner: "sonarr"
    group: "sonarr"
  when: not soco.stat.exists

- name: Configure UrlBase in Sonarr (no config file)
  ansible.builtin.copy:
    src: sonarr-config.xml
    dest: /var/lib/sonarr/config.xml
    mode: "0644"
    owner: sonarr
    group: sonarr
  when: not soco.stat.exists
