---
name: Release
"on":
  push:
    tags:
      - "*"
env:
  PY_COLORS: "1"
  ANSIBLE_FORCE_COLOR: "1"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Setup Python 3
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Install Ansible
        run: >
          pip3 install ansible-core

      - name: Show versions
        run: ansible --version

      - name: Trigger Galaxy import
        run: |
          set -e
          ansible-galaxy role import --api-key ${{ secrets.GALAXY_API_KEY }} \
          --role-name $(echo ${{ github.repository }} | cut -d/ -f2 | cut -d- -f3) \
          $(echo ${{ github.repository }} | cut -d/ -f1) \
          $(echo ${{ github.repository }} | cut -d/ -f2)
